### ISSUE TITLE
Changing the size and number of hexes

### ISSUE THREAD

**Issue by senorhesles** [bennycheung/D3HexMap#2]
@bennycheung  I am trying to use more (and smaller) hexes. I found a world-50m.json file [here](https://github.com/d3/d3.github.com/blob/master/world-50m.v1.json)

Where would you suggest looking in the source for D3HexMap to change the size and number of the hexes? I see that `world-110m.json` is referenced in `js/hexmap/globe.js`; what else would need to be changed to utilize the increased detail found in `world-50m.v1.json`?

**Comment by senorhesles** [comment]
I managed to figure it out. It's pretty easy! You just set the value of the 3rd parameter in `makeHexBinMap` to a smaller value.

My browser complains, but it does what I want!

**Comment by senorhesles** [comment]
This isn't going to get nearly small enough.

What do you think I would need to get hexagons that are 6-miles across (from flat edge to flat edge)? I'm talking from a big picture point of view. I don't care about rendering all of the hexagons at once, only those within view. Do you think I would have to pre-render stuff and cache things to make it performant?

Using a size of `1` appears to get me hexagons that are ~50mi across.

**Comment by bennycheung** [comment]
> @bennycheung I am trying to use more (and smaller) hexes. I found a world-50m.json file [here](https://github.com/d3/d3.github.com/blob/master/world-50m.v1.json)
> 
> Where would you suggest looking in the source for D3HexMap to change the size and number of the hexes? I see that `world-110m.json` is referenced in `js/hexmap/globe.js`; what else would need to be changed to utilize the increased detail found in `world-50m.v1.json`?

You can use smaller resolution world coverage. As you go to higher resolution, you could possibly consuming a lot of memory. In this case, going to 50m means at least 4x more memory requirements.

**Comment by bennycheung** [comment]
> This isn't going to get nearly small enough.
> 
> What do you think I would need to do to get hexagons that are 6-miles across (from flat edge to flat edge)? I'm talking from a big picture point of view. I don't care about rendering all of the hexagons at once, only those within view. Do you think I would have to pre-render stuff and cache things to make it performant?
> 
> Using a size of `1` appears to get me hexagons that are ~17mi across.

In terms of memory consumption, you need a smarter way to manage the data loading and rendering. Of course, my demo code just assumed everything is fitting into memory. Also, depending on what you're trying to achieve, the pre-computation and caching are definitely a consideration. Computational Geometry is all about data structure and efficient algorithm if you want to discover the big picture. GIS (Geographic Information System) is full of advices to handle huge amount geometry data.

**Comment by senorhesles** [comment]
@bennycheung thanks for getting back to me so quickly.

You're right...going down to a resolution of `1` consumes about `10-12Gi` of memory. Do you have any learning resources you would suggest?

The ultimate goal is to tile the Earth with hexagons/pseudo-hexagons of equal area (reference hexagon with sides of 6tan(30) miles, so area of ~31.176 square miles) and render a maximum of ~40x40 of them at the same time (so not many). Each of the hexagons would have a unique id, Koppen-Geiger data and height.

**Comment by bennycheung** [comment]
> @bennycheung thanks for getting back to me so quickly.
> 
> You're right...going down to a resolution of `1` consumes about `10-12Gi` of memory. Do you have any learning resources you would suggest?
> 
> The ultimate goal is to tile the Earth with hexagons/pseudo-hexagons of equal area (reference hexagon with sides of 6tan(30 degrees) miles, so area of ~31.176 square miles) and render a maximum of ~40x40 of them at the same time (so not many). Each of the hexagons would have a unique id, Koppen-Geiger data and height, and potentially textual data manually entered in by a user.

This is well studied area to cover the globe -
read "Geodesic Discrete Global Grid Systems" by Kevin Sahr, Denis White, and A. Jon Kimerling

You can find it here...
http://webpages.sou.edu/~sahrk/dgg/pubs/gdggs03.pdf

**Comment by senorhesles** [comment]
Yes I have familiar with that paper. The issue is that ISEA3H uses particular aperture sizes and resolutions, and the resolutions won't work in my use case.

**Comment by bennycheung** [comment]
Looks like you're a professional researcher in this area, that's awesome. I hope you find success!
Please show me your result if it is publishable, looking forward to that.

**Comment by senorhesles** [comment]
I'm not; just another regular guy.

I'm going to use dggrid. Professor Sahr released a new version of it since the last time I used it. Now you can use a sequence of different apertures; so instead of being restricted to ISEA3H, ISEA4H, or ISEA34H, you can have an arbitrary sequence of apertures of size 3, 4, or 7.

I've determined I need roughly 6,300,000 cells to get hexagons that are ~31 square miles in area. Now I just need to figure out how to determine the number of cells you'd get given a sequence of apertures.
